name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

        - name: Build project with Maven
          run: mvn -B package --file pom.xml

      - name: Build and install project with Maven
        run: |
          mvn clean install
          mvn package
        working-directory: ./Port-Application
